<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    <UserSecretsId>ntmc-scheduler-web-2026</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../NtmcScheduler.Contracts/NtmcScheduler.Contracts.csproj" />
    <ProjectReference Include="../NtmcScheduler.Infrastructure/NtmcScheduler.Infrastructure.csproj" />
    <ProjectReference Include="../NtmcScheduler.Migrations.Sqlite/NtmcScheduler.Migrations.Sqlite.csproj" />
    <ProjectReference Include="../NtmcScheduler.Migrations.SqlServer/NtmcScheduler.Migrations.SqlServer.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>
