// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NtmScheduler.Infrastructure.Data;

#nullable disable

namespace NtmScheduler.Infrastructure.Data.Migrations
{
    [DbContext(typeof(NtmDbContext))]
    [Migration("20260805034006_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("NtmScheduler.Infrastructure.Data.Entities.Assignment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OwnerType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerType", "OwnerId");

                    b.HasIndex("OwnerType", "OwnerId", "EmployeeId", "Date")
                        .IsUnique();

                    b.ToTable("Assignments");
                });

            modelBuilder.Entity("NtmScheduler.Infrastructure.Data.Entities.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("AfterJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("At")
                        .HasColumnType("TEXT");

                    b.Property<string>("BeforeJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("At");

                    b.HasIndex("TargetType", "TargetId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("NtmScheduler.Infrastructure.Data.Entities.CandidateSolution", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CoverageCsv")
                        .HasColumnType("TEXT");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsShortageAnalysis")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MetricsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("RunId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ViolationsCsv")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RunId", "Index")
                        .IsUnique();

                    b.ToTable("CandidateSolutions");
                });

            modelBuilder.Entity("NtmScheduler.Infrastructure.Data.Entities.DraftEdit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AfterState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("At")
                        .HasColumnType("TEXT");

                    b.Property<string>("BeforeState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<long>("DraftId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Seq")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DraftId", "Seq")
                        .IsUnique();

                    b.ToTable("DraftEdits");
                });

            modelBuilder.Entity("NtmScheduler.Infrastructure.Data.Entities.DraftSchedule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<long>("RunId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SourceCandidateId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RunId");

                    b.HasIndex("SourceCandidateId");

                    b.ToTable("DraftSchedules");
                });

            modelBuilder.Entity("NtmScheduler.Infrastructure.Data.Entities.Employee", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Ability")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HomeStation")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Specialty")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("NtmScheduler.Infrastructure.Data.Entities.EmployeeMonthlyShift", b =>
                {
                    b.Property<string>("EmployeeId")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Month")
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<string>("Shift")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.HasKey("EmployeeId", "Month");

                    b.ToTable("EmployeeMonthlyShifts");
                });

            modelBuilder.Entity("NtmScheduler.Infrastructure.Data.Entities.FixedEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("End")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Start")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId", "Type", "Date");

                    b.ToTable("FixedEvents");
                });

            modelBuilder.Entity("NtmScheduler.Infrastructure.Data.Entities.OfficialScheduleVersion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<int>("VersionNo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Unit", "Month", "IsCurrent");

                    b.HasIndex("Unit", "Month", "VersionNo")
                        .IsUnique();

                    b.ToTable("OfficialScheduleVersions");
                });

            modelBuilder.Entity("NtmScheduler.Infrastructure.Data.Entities.RuleSetting", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ParametersJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RuleId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Unit", "RuleId")
                        .IsUnique();

                    b.ToTable("RuleSettings");
                });

            modelBuilder.Entity("NtmScheduler.Infrastructure.Data.Entities.ScheduleCycle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("End")
                        .HasColumnType("TEXT");

                    b.Property<int>("RequiredR")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(16);

                    b.Property<int>("RequiredR1")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Start")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Start")
                        .IsUnique();

                    b.ToTable("ScheduleCycles");
                });

            modelBuilder.Entity("NtmScheduler.Infrastructure.Data.Entities.ScheduleRun", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CandidateCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("OptimizationStatus")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProgramVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProgressJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ScheduleStatus")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("Seed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShortageAnalysisAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetMonth")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Unit", "TargetMonth", "CreatedAt");

                    b.ToTable("ScheduleRuns");
                });

            modelBuilder.Entity("NtmScheduler.Infrastructure.Data.Entities.CandidateSolution", b =>
                {
                    b.HasOne("NtmScheduler.Infrastructure.Data.Entities.ScheduleRun", "Run")
                        .WithMany("Candidates")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("NtmScheduler.Infrastructure.Data.Entities.DraftEdit", b =>
                {
                    b.HasOne("NtmScheduler.Infrastructure.Data.Entities.DraftSchedule", "Draft")
                        .WithMany("Edits")
                        .HasForeignKey("DraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Draft");
                });

            modelBuilder.Entity("NtmScheduler.Infrastructure.Data.Entities.DraftSchedule", b =>
                {
                    b.HasOne("NtmScheduler.Infrastructure.Data.Entities.ScheduleRun", "Run")
                        .WithMany("Drafts")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NtmScheduler.Infrastructure.Data.Entities.CandidateSolution", "SourceCandidate")
                        .WithMany()
                        .HasForeignKey("SourceCandidateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Run");

                    b.Navigation("SourceCandidate");
                });

            modelBuilder.Entity("NtmScheduler.Infrastructure.Data.Entities.EmployeeMonthlyShift", b =>
                {
                    b.HasOne("NtmScheduler.Infrastructure.Data.Entities.Employee", "Employee")
                        .WithMany("MonthlyShifts")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("NtmScheduler.Infrastructure.Data.Entities.FixedEvent", b =>
                {
                    b.HasOne("NtmScheduler.Infrastructure.Data.Entities.Employee", "Employee")
                        .WithMany("FixedEvents")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("NtmScheduler.Infrastructure.Data.Entities.DraftSchedule", b =>
                {
                    b.Navigation("Edits");
                });

            modelBuilder.Entity("NtmScheduler.Infrastructure.Data.Entities.Employee", b =>
                {
                    b.Navigation("FixedEvents");

                    b.Navigation("MonthlyShifts");
                });

            modelBuilder.Entity("NtmScheduler.Infrastructure.Data.Entities.ScheduleRun", b =>
                {
                    b.Navigation("Candidates");

                    b.Navigation("Drafts");
                });
#pragma warning restore 612, 618
        }
    }
}
