// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NtmcScheduler.Infrastructure.Data;

#nullable disable

namespace NtmcScheduler.Infrastructure.Data.Migrations
{
    [DbContext(typeof(NtmcDbContext))]
    [Migration("20260813093555_DeleteEmployeeArchiveFlag")]
    partial class DeleteEmployeeArchiveFlag
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        ;

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        ;

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        ;

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<string>("ClaimType")
                        ;

                    b.Property<string>("ClaimValue")
                        ;

                    b.Property<Guid>("RoleId")
                        ;

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<string>("ClaimType")
                        ;

                    b.Property<string>("ClaimValue")
                        ;

                    b.Property<Guid>("UserId")
                        ;

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        ;

                    b.Property<string>("ProviderKey")
                        ;

                    b.Property<string>("ProviderDisplayName")
                        ;

                    b.Property<Guid>("UserId")
                        ;

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        ;

                    b.Property<Guid>("RoleId")
                        ;

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        ;

                    b.Property<string>("LoginProvider")
                        ;

                    b.Property<string>("Name")
                        ;

                    b.Property<string>("Value")
                        ;

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("NtmcScheduler.Infrastructure.Data.AdoptedSchedule", b =>
                {
                    b.Property<string>("Workspace")
                        .HasMaxLength(1)
                        ;

                    b.Property<DateOnly>("Month")
                        ;

                    b.Property<DateTimeOffset>("AdoptedAtUtc")
                        ;

                    b.Property<Guid>("AdoptedByUserId")
                        ;

                    b.Property<Guid>("ScheduleVersionId")
                        ;

                    b.HasKey("Workspace", "Month");

                    b.HasIndex("ScheduleVersionId")
                        .IsUnique();

                    b.ToTable("AdoptedSchedules");
                });

            modelBuilder.Entity("NtmcScheduler.Infrastructure.Data.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<int>("AccessFailedCount")
                        ;

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        ;

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        ;

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        ;

                    b.Property<bool>("EmailConfirmed")
                        ;

                    b.Property<bool>("IsDisabled")
                        ;

                    b.Property<bool>("LockoutEnabled")
                        ;

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        ;

                    b.Property<bool>("MustChangePassword")
                        ;

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        ;

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(100)
                        ;

                    b.Property<string>("PasswordHash")
                        ;

                    b.Property<string>("PhoneNumber")
                        ;

                    b.Property<bool>("PhoneNumberConfirmed")
                        ;

                    b.Property<string>("SecurityStamp")
                        ;

                    b.Property<bool>("TwoFactorEnabled")
                        ;

                    b.Property<string>("UserName")
                        .HasMaxLength(100)
                        ;

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("NtmcScheduler.Infrastructure.Data.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(80)
                        ;

                    b.Property<string>("ActorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        ;

                    b.Property<Guid?>("ActorUserId")
                        ;

                    b.Property<string>("AfterJson")
                        ;

                    b.Property<DateTimeOffset>("AtUtc")
                        ;

                    b.Property<long>("AtUtcTicks")
                        ;

                    b.Property<string>("BeforeJson")
                        ;

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        ;

                    b.Property<string>("IpAddress")
                        ;

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasMaxLength(80)
                        ;

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(80)
                        ;

                    b.Property<bool>("Succeeded")
                        ;

                    b.Property<string>("UserAgent")
                        ;

                    b.Property<int?>("Workspace")
                        ;

                    b.HasKey("Id");

                    b.HasIndex("AtUtcTicks");

                    b.HasIndex("Workspace", "Action");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("NtmcScheduler.Infrastructure.Data.ConfigurationRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        ;

                    b.Property<Guid>("CreatedByUserId")
                        ;

                    b.Property<int>("Version")
                        ;

                    b.HasKey("Id");

                    b.HasIndex("Version")
                        .IsUnique();

                    b.ToTable("ConfigurationRevisions");
                });

            modelBuilder.Entity("NtmcScheduler.Infrastructure.Data.CurrentConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<Guid>("ConfigurationRevisionId")
                        ;

                    b.Property<Guid>("RevisionToken")
                        .IsConcurrencyToken()
                        ;

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationRevisionId");

                    b.ToTable("CurrentConfigurations");
                });

            modelBuilder.Entity("NtmcScheduler.Infrastructure.Data.DemandAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<DateOnly>("Date")
                        ;

                    b.Property<Guid>("DemandEmployeeId")
                        ;

                    b.Property<string>("EventDescription")
                        ;

                    b.Property<DateTimeOffset?>("EventEnd")
                        ;

                    b.Property<DateTimeOffset?>("EventStart")
                        ;

                    b.Property<string>("Kind")
                        ;

                    b.Property<bool>("RequestedRest")
                        ;

                    b.Property<string>("Shift")
                        ;

                    b.Property<string>("Station")
                        ;

                    b.HasKey("Id");

                    b.HasIndex("DemandEmployeeId", "Date")
                        .IsUnique();

                    b.ToTable("DemandAssignments");
                });

            modelBuilder.Entity("NtmcScheduler.Infrastructure.Data.DemandDraft", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<Guid>("ConfigurationRevisionId")
                        ;

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        ;

                    b.Property<Guid>("CreatedByUserId")
                        ;

                    b.Property<DateOnly>("Month")
                        ;

                    b.Property<string>("PerpetualScheduleJson")
                        ;

                    b.Property<Guid?>("PreviousAdoptedScheduleVersionId")
                        ;

                    b.Property<string>("PreviousSource")
                        .IsRequired()
                        .HasMaxLength(32)
                        ;

                    b.Property<Guid>("RevisionToken")
                        .IsConcurrencyToken()
                        ;

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        ;

                    b.Property<Guid>("UpdatedByUserId")
                        ;

                    b.Property<Guid?>("UploadedPreviousScheduleId")
                        ;

                    b.Property<string>("Workspace")
                        .IsRequired()
                        .HasMaxLength(1)
                        ;

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationRevisionId");

                    b.HasIndex("UploadedPreviousScheduleId");

                    b.HasIndex("Workspace", "Month")
                        .IsUnique();

                    b.ToTable("DemandDrafts");
                });

            modelBuilder.Entity("NtmcScheduler.Infrastructure.Data.DemandEmployee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<int?>("Ability")
                        ;

                    b.Property<string>("Affiliation")
                        .IsRequired()
                        .HasMaxLength(64)
                        ;

                    b.Property<Guid>("DemandDraftId")
                        ;

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        ;

                    b.Property<DateOnly?>("EmploymentStartDate")
                        ;

                    b.Property<string>("MonthlyShift")
                        ;

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        ;

                    b.Property<int?>("OpeningRest")
                        ;

                    b.Property<int?>("OpeningSpecialRest")
                        ;

                    b.Property<string>("PerpetualScheduleId")
                        ;

                    b.Property<int>("RequestedLeaveRestCount")
                        ;

                    b.HasKey("Id");

                    b.HasIndex("DemandDraftId", "EmployeeCode")
                        .IsUnique();

                    b.ToTable("DemandEmployees");
                });

            modelBuilder.Entity("NtmcScheduler.Infrastructure.Data.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<int?>("Ability")
                        ;

                    b.Property<string>("Affiliation")
                        .IsRequired()
                        .HasMaxLength(64)
                        ;

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        ;

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        ;

                    b.Property<DateOnly?>("EmploymentStartDate")
                        ;

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        ;

                    b.Property<Guid>("RevisionToken")
                        .IsConcurrencyToken()
                        ;

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        ;

                    b.Property<string>("Workspace")
                        .IsRequired()
                        .HasMaxLength(1)
                        ;

                    b.HasKey("Id");

                    b.HasIndex("Workspace", "EmployeeCode")
                        .IsUnique();

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("NtmcScheduler.Infrastructure.Data.ExternalAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<int>("Count")
                        ;

                    b.Property<DateOnly>("Date")
                        ;

                    b.Property<Guid>("ScheduleVersionId")
                        ;

                    b.Property<string>("Shift")
                        .IsRequired()
                        ;

                    b.Property<string>("Station")
                        .IsRequired()
                        ;

                    b.HasKey("Id");

                    b.HasIndex("ScheduleVersionId");

                    b.ToTable("ExternalAssignments");
                });

            modelBuilder.Entity("NtmcScheduler.Infrastructure.Data.NationalHoliday", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<DateOnly>("Date")
                        ;

                    b.Property<Guid>("RestIntervalId")
                        ;

                    b.HasKey("Id");

                    b.HasIndex("RestIntervalId", "Date")
                        .IsUnique();

                    b.ToTable("NationalHolidays");
                });

            modelBuilder.Entity("NtmcScheduler.Infrastructure.Data.NonStandardShiftEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        ;

                    b.Property<Guid>("ConfigurationRevisionId")
                        ;

                    b.Property<TimeOnly>("EndTime")
                        ;

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        ;

                    b.Property<TimeOnly>("StartTime")
                        ;

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationRevisionId", "Code")
                        .IsUnique();

                    b.ToTable("NonStandardShifts");
                });

            modelBuilder.Entity("NtmcScheduler.Infrastructure.Data.RestIntervalEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<Guid>("ConfigurationRevisionId")
                        ;

                    b.Property<DateOnly>("End")
                        ;

                    b.Property<DateOnly>("Start")
                        ;

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationRevisionId", "Start")
                        .IsUnique();

                    b.ToTable("RestIntervals");
                });

            modelBuilder.Entity("NtmcScheduler.Infrastructure.Data.ScheduleAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<DateOnly>("Date")
                        ;

                    b.Property<string>("EventDescription")
                        ;

                    b.Property<DateTimeOffset?>("EventEnd")
                        ;

                    b.Property<DateTimeOffset?>("EventStart")
                        ;

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        ;

                    b.Property<bool>("RequestedRest")
                        ;

                    b.Property<Guid>("ScheduleEmployeeSnapshotId")
                        ;

                    b.Property<string>("Shift")
                        ;

                    b.Property<string>("Station")
                        ;

                    b.HasKey("Id");

                    b.HasIndex("ScheduleEmployeeSnapshotId", "Date")
                        .IsUnique();

                    b.ToTable("ScheduleAssignments");
                });

            modelBuilder.Entity("NtmcScheduler.Infrastructure.Data.ScheduleEmployeeSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<int?>("Ability")
                        ;

                    b.Property<string>("Affiliation")
                        .IsRequired()
                        ;

                    b.Property<int?>("ClosingRest")
                        ;

                    b.Property<int?>("ClosingSpecialRest")
                        ;

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        ;

                    b.Property<DateOnly?>("EmploymentStartDate")
                        ;

                    b.Property<string>("MonthlyShift")
                        ;

                    b.Property<string>("Name")
                        .IsRequired()
                        ;

                    b.Property<int?>("NormalWorkCount")
                        ;

                    b.Property<int?>("OpeningRest")
                        ;

                    b.Property<int?>("OpeningSpecialRest")
                        ;

                    b.Property<string>("PerpetualScheduleId")
                        ;

                    b.Property<int>("RequestedLeaveRestCount")
                        ;

                    b.Property<Guid>("ScheduleVersionId")
                        ;

                    b.HasKey("Id");

                    b.HasIndex("ScheduleVersionId", "EmployeeCode")
                        .IsUnique();

                    b.ToTable("ScheduleEmployeeSnapshots");
                });

            modelBuilder.Entity("NtmcScheduler.Infrastructure.Data.ScheduleRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        ;

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        ;

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        ;

                    b.Property<Guid>("DemandDraftId")
                        ;

                    b.Property<string>("Error")
                        ;

                    b.Property<string>("InputHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        ;

                    b.Property<string>("InputSnapshotJson")
                        .IsRequired()
                        ;

                    b.Property<string>("IpAddress")
                        ;

                    b.Property<DateOnly>("Month")
                        ;

                    b.Property<string>("PerpetualScheduleJson")
                        ;

                    b.Property<string>("ProgramVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        ;

                    b.Property<int>("RandomSeed")
                        ;

                    b.Property<string>("RequestedByName")
                        .IsRequired()
                        .HasMaxLength(100)
                        ;

                    b.Property<Guid>("RequestedByUserId")
                        ;

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        ;

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        ;

                    b.Property<int>("TimeLimitSeconds")
                        ;

                    b.Property<string>("UserAgent")
                        ;

                    b.Property<int>("WorkerCount")
                        ;

                    b.Property<string>("Workspace")
                        .IsRequired()
                        .HasMaxLength(1)
                        ;

                    b.HasKey("Id");

                    b.HasIndex("Workspace", "Month", "CreatedAtUtc");

                    b.ToTable("ScheduleRuns");
                });

            modelBuilder.Entity("NtmcScheduler.Infrastructure.Data.ScheduleVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<int?>("CandidateIndex")
                        ;

                    b.Property<Guid>("ConfigurationRevisionId")
                        ;

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        ;

                    b.Property<Guid>("CreatedByUserId")
                        ;

                    b.Property<bool>("HasErrors")
                        ;

                    b.Property<bool>("IsArchived")
                        ;

                    b.Property<DateOnly>("Month")
                        ;

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        ;

                    b.Property<Guid>("RevisionToken")
                        .IsConcurrencyToken()
                        ;

                    b.Property<Guid?>("SourceRunId")
                        ;

                    b.Property<string>("SourceStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        ;

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        ;

                    b.Property<Guid>("UpdatedByUserId")
                        ;

                    b.Property<int>("WarningCount")
                        ;

                    b.Property<string>("Workspace")
                        .IsRequired()
                        .HasMaxLength(1)
                        ;

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationRevisionId");

                    b.HasIndex("SourceRunId");

                    b.HasIndex("Workspace", "Month", "CreatedAtUtc");

                    b.ToTable("ScheduleVersions");
                });

            modelBuilder.Entity("NtmcScheduler.Infrastructure.Data.UploadedPreviousSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        ;

                    b.Property<DateOnly>("Month")
                        ;

                    b.Property<string>("ParsedScheduleJson")
                        .IsRequired()
                        ;

                    b.Property<string>("Workspace")
                        .IsRequired()
                        .HasMaxLength(1)
                        ;

                    b.HasKey("Id");

                    b.ToTable("UploadedPreviousSchedules");
                });

            modelBuilder.Entity("NtmcScheduler.Infrastructure.Data.WorkspacePermission", b =>
                {
                    b.Property<Guid>("UserId")
                        ;

                    b.Property<string>("Workspace")
                        .HasMaxLength(1)
                        ;

                    b.HasKey("UserId", "Workspace");

                    b.ToTable("WorkspacePermissions");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("NtmcScheduler.Infrastructure.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("NtmcScheduler.Infrastructure.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NtmcScheduler.Infrastructure.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("NtmcScheduler.Infrastructure.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NtmcScheduler.Infrastructure.Data.AdoptedSchedule", b =>
                {
                    b.HasOne("NtmcScheduler.Infrastructure.Data.ScheduleVersion", "ScheduleVersion")
                        .WithMany()
                        .HasForeignKey("ScheduleVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ScheduleVersion");
                });

            modelBuilder.Entity("NtmcScheduler.Infrastructure.Data.CurrentConfiguration", b =>
                {
                    b.HasOne("NtmcScheduler.Infrastructure.Data.ConfigurationRevision", "ConfigurationRevision")
                        .WithMany()
                        .HasForeignKey("ConfigurationRevisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ConfigurationRevision");
                });

            modelBuilder.Entity("NtmcScheduler.Infrastructure.Data.DemandAssignment", b =>
                {
                    b.HasOne("NtmcScheduler.Infrastructure.Data.DemandEmployee", "DemandEmployee")
                        .WithMany("Assignments")
                        .HasForeignKey("DemandEmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DemandEmployee");
                });

            modelBuilder.Entity("NtmcScheduler.Infrastructure.Data.DemandDraft", b =>
                {
                    b.HasOne("NtmcScheduler.Infrastructure.Data.ConfigurationRevision", "ConfigurationRevision")
                        .WithMany()
                        .HasForeignKey("ConfigurationRevisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NtmcScheduler.Infrastructure.Data.UploadedPreviousSchedule", "UploadedPreviousSchedule")
                        .WithMany()
                        .HasForeignKey("UploadedPreviousScheduleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ConfigurationRevision");

                    b.Navigation("UploadedPreviousSchedule");
                });

            modelBuilder.Entity("NtmcScheduler.Infrastructure.Data.DemandEmployee", b =>
                {
                    b.HasOne("NtmcScheduler.Infrastructure.Data.DemandDraft", "DemandDraft")
                        .WithMany("Employees")
                        .HasForeignKey("DemandDraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DemandDraft");
                });

            modelBuilder.Entity("NtmcScheduler.Infrastructure.Data.ExternalAssignment", b =>
                {
                    b.HasOne("NtmcScheduler.Infrastructure.Data.ScheduleVersion", "ScheduleVersion")
                        .WithMany("ExternalAssignments")
                        .HasForeignKey("ScheduleVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScheduleVersion");
                });

            modelBuilder.Entity("NtmcScheduler.Infrastructure.Data.NationalHoliday", b =>
                {
                    b.HasOne("NtmcScheduler.Infrastructure.Data.RestIntervalEntity", "RestInterval")
                        .WithMany("NationalHolidays")
                        .HasForeignKey("RestIntervalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RestInterval");
                });

            modelBuilder.Entity("NtmcScheduler.Infrastructure.Data.NonStandardShiftEntity", b =>
                {
                    b.HasOne("NtmcScheduler.Infrastructure.Data.ConfigurationRevision", "ConfigurationRevision")
                        .WithMany("NonStandardShifts")
                        .HasForeignKey("ConfigurationRevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConfigurationRevision");
                });

            modelBuilder.Entity("NtmcScheduler.Infrastructure.Data.RestIntervalEntity", b =>
                {
                    b.HasOne("NtmcScheduler.Infrastructure.Data.ConfigurationRevision", "ConfigurationRevision")
                        .WithMany("RestIntervals")
                        .HasForeignKey("ConfigurationRevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConfigurationRevision");
                });

            modelBuilder.Entity("NtmcScheduler.Infrastructure.Data.ScheduleAssignment", b =>
                {
                    b.HasOne("NtmcScheduler.Infrastructure.Data.ScheduleEmployeeSnapshot", "Employee")
                        .WithMany("Assignments")
                        .HasForeignKey("ScheduleEmployeeSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("NtmcScheduler.Infrastructure.Data.ScheduleEmployeeSnapshot", b =>
                {
                    b.HasOne("NtmcScheduler.Infrastructure.Data.ScheduleVersion", "ScheduleVersion")
                        .WithMany("Employees")
                        .HasForeignKey("ScheduleVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScheduleVersion");
                });

            modelBuilder.Entity("NtmcScheduler.Infrastructure.Data.ScheduleVersion", b =>
                {
                    b.HasOne("NtmcScheduler.Infrastructure.Data.ConfigurationRevision", "ConfigurationRevision")
                        .WithMany()
                        .HasForeignKey("ConfigurationRevisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NtmcScheduler.Infrastructure.Data.ScheduleRun", "SourceRun")
                        .WithMany("Versions")
                        .HasForeignKey("SourceRunId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ConfigurationRevision");

                    b.Navigation("SourceRun");
                });

            modelBuilder.Entity("NtmcScheduler.Infrastructure.Data.WorkspacePermission", b =>
                {
                    b.HasOne("NtmcScheduler.Infrastructure.Data.ApplicationUser", "User")
                        .WithMany("WorkspacePermissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NtmcScheduler.Infrastructure.Data.ApplicationUser", b =>
                {
                    b.Navigation("WorkspacePermissions");
                });

            modelBuilder.Entity("NtmcScheduler.Infrastructure.Data.ConfigurationRevision", b =>
                {
                    b.Navigation("NonStandardShifts");

                    b.Navigation("RestIntervals");
                });

            modelBuilder.Entity("NtmcScheduler.Infrastructure.Data.DemandDraft", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("NtmcScheduler.Infrastructure.Data.DemandEmployee", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("NtmcScheduler.Infrastructure.Data.RestIntervalEntity", b =>
                {
                    b.Navigation("NationalHolidays");
                });

            modelBuilder.Entity("NtmcScheduler.Infrastructure.Data.ScheduleEmployeeSnapshot", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("NtmcScheduler.Infrastructure.Data.ScheduleRun", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("NtmcScheduler.Infrastructure.Data.ScheduleVersion", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("ExternalAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
